// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvPnP95nCo9AYhe3eewYgLnwGFuYlEAOk',
    appId: '1:896662708597:web:464caccf173c138997333c',
    messagingSenderId: '896662708597',
    projectId: 'agua-2a580',
    authDomain: 'agua-2a580.firebaseapp.com',
    storageBucket: 'agua-2a580.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfkh1piJTDNseUN0xBskR3NNcfwBIMjZ8',
    appId: '1:896662708597:android:4c6831ee0d8a35de97333c',
    messagingSenderId: '896662708597',
    projectId: 'agua-2a580',
    storageBucket: 'agua-2a580.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjIiMuilTDkxAmYdlmFIxGfV0VjeKMzNw',
    appId: '1:896662708597:ios:9bec90f2494547e497333c',
    messagingSenderId: '896662708597',
    projectId: 'agua-2a580',
    storageBucket: 'agua-2a580.appspot.com',
    iosBundleId: 'life.frescon.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjIiMuilTDkxAmYdlmFIxGfV0VjeKMzNw',
    appId: '1:896662708597:ios:9bec90f2494547e497333c',
    messagingSenderId: '896662708597',
    projectId: 'agua-2a580',
    storageBucket: 'agua-2a580.appspot.com',
    iosBundleId: 'life.frescon.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvPnP95nCo9AYhe3eewYgLnwGFuYlEAOk',
    appId: '1:896662708597:web:a3eee015392a037697333c',
    messagingSenderId: '896662708597',
    projectId: 'agua-2a580',
    authDomain: 'agua-2a580.firebaseapp.com',
    storageBucket: 'agua-2a580.appspot.com',
  );
}
